from django.urls import path
from .views import (
    AdminAppointmentStatusUpdateView,
    AdminBookingDocumentListCreateView,
    AdminDocumentDeleteView,
    AdminRegisterView,
    AdminHospitalUpdateView,
    AdminOverviewView,
    AdminProfileView,
    AdminPatientRecordListCreateView,
    AdminPatientRecordUpdateView,
    AdminTransferView,
    AnalyzeSymptomsView,
    BookAppointmentView,
    DocumentDownloadView,
    DoctorsByHospitalView,
    HealthCheckView,
    HospitalSelfUpdateView,
    HospitalRecommendationsView,
    LoginView,
    LogoutView,
    PatientAppointmentStatusView,
    PatientDashboardView,
    PatientDocumentDeleteView,
    PatientDocumentListCreateView,
    PatientRecordDeleteView,
    PatientSosAlertView,
    PatientSosAlertDetailView,
    SessionView,
)

urlpatterns = [
    path("health", HealthCheckView.as_view(), name="health"),
    path("auth/admin-register", AdminRegisterView.as_view(), name="auth-admin-register"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/session", SessionView.as_view(), name="auth-session"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("analyze-symptoms", AnalyzeSymptomsView.as_view(), name="analyze-symptoms"),
    path(
        "hospitals/recommendations",
        HospitalRecommendationsView.as_view(),
        name="hospital-recommendations",
    ),
    path(
        "doctors/by-hospital",
        DoctorsByHospitalView.as_view(),
        name="doctors-by-hospital",
    ),
    path("book-appointment", BookAppointmentView.as_view(), name="book-appointment"),
    path("patient/dashboard", PatientDashboardView.as_view(), name="patient-dashboard"),
    path("patient/documents", PatientDocumentListCreateView.as_view(), name="patient-document-list-create"),
    path("patient/documents/<int:document_id>", PatientDocumentDeleteView.as_view(), name="patient-document-delete"),
    path(
        "patient/appointments/<int:booking_id>/status",
        PatientAppointmentStatusView.as_view(),
        name="patient-appointment-status",
    ),
    path(
        "patient/records/<int:booking_id>",
        PatientRecordDeleteView.as_view(),
        name="patient-record-delete",
    ),
    path("patient/sos-alerts", PatientSosAlertView.as_view(), name="patient-sos-alerts"),
    path(
        "patient/sos-alerts/<int:alert_id>",
        PatientSosAlertDetailView.as_view(),
        name="patient-sos-alert-detail",
    ),
    path("admin/overview", AdminOverviewView.as_view(), name="admin-overview"),
    path("admin/profile", AdminProfileView.as_view(), name="admin-profile"),
    path("hospital/update", HospitalSelfUpdateView.as_view(), name="hospital-self-update"),
    path(
        "admin/appointments/<int:booking_id>/status",
        AdminAppointmentStatusUpdateView.as_view(),
        name="admin-appointment-status-update",
    ),
    path(
        "admin/patient-records",
        AdminPatientRecordListCreateView.as_view(),
        name="admin-patient-record-create",
    ),
    path(
        "admin/hospitals/<int:hospital_id>",
        AdminHospitalUpdateView.as_view(),
        name="admin-hospital-update",
    ),
    path(
        "admin/patient-records/<int:booking_id>",
        AdminPatientRecordUpdateView.as_view(),
        name="admin-patient-record-update",
    ),
    path(
        "admin/patient-records/<int:booking_id>/documents",
        AdminBookingDocumentListCreateView.as_view(),
        name="admin-patient-record-document-create",
    ),
    path("admin/documents/<int:document_id>", AdminDocumentDeleteView.as_view(), name="admin-document-delete"),
    path("admin/transfers", AdminTransferView.as_view(), name="admin-transfers"),
    path("documents/<int:document_id>/download", DocumentDownloadView.as_view(), name="document-download"),
]
