# Generated by Django 6.0.3 on 2026-04-03 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sosalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='booking',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='next_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='recommended_specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('under_review', 'Under Review'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='location_context',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='critical', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='HospitalAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hospital Operations Admin', max_length=120)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='core.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterHospitalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('report_body', models.TextField()),
                ('report_format', models.CharField(default='PDF', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('share_mode', models.CharField(choices=[('email', 'Encrypted Email'), ('api', 'Secure API')], default='api', max_length=10)),
                ('access_scope', models.CharField(default='Limited clinical view', max_length=120)),
                ('receiving_team', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('report_generated', 'Report Generated'), ('shared', 'Shared'), ('access_granted', 'Access Granted'), ('continuity_of_care', 'Continuity Of Care')], default='report_generated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='core.hospitaladminprofile')),
                ('source_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='core.hospital')),
                ('target_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='core.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='core.patientprofile'),
        ),
    ]
